


services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    expose:
      - "3306"
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    expose:
      - "9000"
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/crocha-s/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      device: /home/crocha-s/data/wp_db
      o: bind
      type: none

networks:
  inception:
    driver: bridge
